### ISSUE TITLE
Get actual prediction results

### ISSUE THREAD

**Issue by timwukp** [aws-samples/lookout-for-equipment-demo#3]
In notebook 5 of inference, for your source code

results_df = scheduler.get_predictions()
results_df.to_csv(os.path.join(INFER_DATA, 'output', 'results.csv'))
results_df

but in S3 output of each inference result, the file is 'results.jsonl', so the error is,

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-0666b1cb1052> in <module>
----> 1 results_df = scheduler.get_predictions()
      2 results_df.to_csv(os.path.join(INFER_DATA, 'output', 'results.jsonl'))
      3 results_df

~/SageMaker/lookout-for-equipment-demo/utils/lookout_equipment_utils.py in get_predictions(self)
   1359         # Assembles them into a DataFrame:
   1360         results_df = pd.concat(results_df, axis='index')
-> 1361         results_df.columns = ['Timestamp', 'Predictions']
   1362         results_df['Timestamp'] = pd.to_datetime(results_df['Timestamp'])
   1363         results_df = results_df.set_index('Timestamp')

~/anaconda3/envs/python3/lib/python3.6/site-packages/pandas/core/generic.py in __setattr__(self, name, value)
   5152         try:
   5153             object.__getattribute__(self, name)
-> 5154             return object.__setattr__(self, name, value)
   5155         except AttributeError:
   5156             pass

pandas/_libs/properties.pyx in pandas._libs.properties.AxisProperty.__set__()

~/anaconda3/envs/python3/lib/python3.6/site-packages/pandas/core/generic.py in _set_axis(self, axis, labels)
    562     def _set_axis(self, axis: int, labels: Index) -> None:
    563         labels = ensure_index(labels)
--> 564         self._mgr.set_axis(axis, labels)
    565         self._clear_item_cache()
    566 

~/anaconda3/envs/python3/lib/python3.6/site-packages/pandas/core/internals/managers.py in set_axis(self, axis, new_labels)
    225         if new_len != old_len:
    226             raise ValueError(
--> 227                 f"Length mismatch: Expected axis has {old_len} elements, new "
    228                 f"values have {new_len} elements"
    229             )

ValueError: Length mismatch: Expected axis has 246 elements, new values have 2 elements

**Comment by michaelhoarau** [comment]
Hi!
Thanks, the service is getting close to the GA date and we changed the output format for the inference scheduler (from CSV to JSON lines).
I've updated this part and need to commit it (hopefully by the end of the week).
Thanks for your insights and your interest for Lookout for Equipment!
Michaël.

**Comment by timwukp** [comment]
sounds good, other notebook are running well.
May I know the meaning of 'diagnostics__value' in the output result file? 
For the prediction = 1, does it mean 'fault' ?

**Comment by michaelhoarau** [comment]
Latest commit updated the scheduled inference to take care of the new format for scheduled inference (CSV to JSON lines).
When prediction is 1, it means that a divergence (i.e. an anomaly) has been found when looking at the multivariate relationship between the different time series data.
