### ISSUE TITLE
Incorrect model name in file getting_started/notebooks/5_inference_scheduling.py

### ISSUE THREAD

**Issue by vanithar75** [aws-samples/lookout-for-equipment-demo#8]
Hi,
This macro should be MODEL_NAME_FOR_CREATING_INFERENCE_SCHEDULER = 'lookout-demo-model-v1' , instead of 'lookout-demo-model-v4'

**Comment by michaelhoarau** [comment]
Thanks for the catch! Corrected with the last commit.
